### ISSUE TITLE
Grouping generates invalid SQL when running a count query

### ISSUE THREAD

**Issue by CyborgMaster** [activerecord-hackery/squeel#286]
It appears that a Squeel group clause doesn't work when running a count query.  I have  a query that looks like the following (simplified): 

``` ruby
grouped = Appointment.joins{patient}.group{patient.id}
```

This works fine if I access the results normally: `grouped.first`.  And generates the following SQL:

``` mysql
SELECT `allysync_development`.`appointments`.* FROM `allysync_development`.`appointments` INNER JOIN `allysync_development`.`patients` ON `allysync_development`.`patients`.`id` = `allysync_development`.`appointments`.`patient_id` GROUP BY `allysync_development`.`patients`.`id` ORDER BY `allysync_development`.`appointments`.`id` ASC LIMIT 1
```

A size operation works as well if the data has already been loaded: `grouped.load.size`.   However, if I run a size operation directly (`grouped.size`), the following invalid SQL is generated: 

``` mysql
SELECT COUNT(*) AS count_all, patient.id AS patient_id FROM `allysync_development`.`appointments` INNER JOIN `allysync_development`.`patients` ON `allysync_development`.`patients`.`id` = `allysync_development`.`appointments`.`patient_id` GROUP BY `allysync_development`.`patients`.`id`
```

It appears as if Squeel isn't evaluating the column name using the relations and it is instead being inserted verbatim as `patient.id` (instead of ``allysync_development`.`patients`.`id``)

**Comment by chewi** [comment]
Unfortunately this breaks the usage of named functions in group.

```
NoMethodError: undefined method `relation' for #<Arel::Nodes::NamedFunction:0x000000031c1580>
```

This happens because Rails checks for a method called `name`, which Arel::Nodes::NamedFunction has but Squeel::Nodes::Function doesn't. If you make it also check for a method called `relation`, it gets further but still blows up.

```
ActiveRecord::StatementInvalid: PG::SyntaxError: ERROR:  syntax error at or near "AS"
... GROUP BY date_trunc('hour', "foo"."created_at") AS arel_nodes_namedfunction_0x00000002e833a0
```

There should be no AS after the GROUP BY. This happens because calling `as` on Arel::Nodes::NamedFunction modifies the object whereas calling it on Squeel::Nodes::Function doesn't. You can replicate this even by passing an Arel::Nodes::NamedFunction straight to group without Squeel's help so I'm tempted to call this a Rails bug.

On a side note, this also causes the deprecation warning in #374.

**Comment by chewi** [comment]
See rails/rails/issues/24207.
